It dies on malformed %YAML directive
What is the FIXME on line 186?
Why is line 216 commented?

Example of breaking code:
```javascript
const y = require('yaml-ast-parser');

y.loadAll(
`%YAML 12
---
a: 123`,
function(){ console.log(require('util').inspect(arguments, false, 10, true)) })
TypeError: Cannot read property '1' of null
```